-- 1.load_application

DROP TABLE IF EXISTS application_train;

CREATE TABLE application_train (
  `SK_ID_CURR` BIGINT,
  `TARGET` BIGINT,
  `NAME_CONTRACT_TYPE` VARCHAR(30),
  `CODE_GENDER` VARCHAR(30),
  `FLAG_OWN_CAR` VARCHAR(30),
  `FLAG_OWN_REALTY` VARCHAR(30),
  `CNT_CHILDREN` BIGINT,
  `AMT_INCOME_TOTAL` DOUBLE,
  `AMT_CREDIT` DOUBLE,
  `AMT_ANNUITY` DOUBLE,
  `AMT_GOODS_PRICE` DOUBLE,
  `NAME_TYPE_SUITE` VARCHAR(30),
  `NAME_INCOME_TYPE` VARCHAR(30),
  `NAME_EDUCATION_TYPE` VARCHAR(39),
  `NAME_FAMILY_STATUS` VARCHAR(30),
  `NAME_HOUSING_TYPE` VARCHAR(30),
  `REGION_POPULATION_RELATIVE` DOUBLE,
  `DAYS_BIRTH` BIGINT,
  `DAYS_EMPLOYED` BIGINT,
  `DAYS_REGISTRATION` DOUBLE,
  `DAYS_ID_PUBLISH` BIGINT,
  `OWN_CAR_AGE` DOUBLE,
  `FLAG_MOBIL` BIGINT,
  `FLAG_EMP_PHONE` BIGINT,
  `FLAG_WORK_PHONE` BIGINT,
  `FLAG_CONT_MOBILE` BIGINT,
  `FLAG_PHONE` BIGINT,
  `FLAG_EMAIL` BIGINT,
  `OCCUPATION_TYPE` VARCHAR(31),
  `CNT_FAM_MEMBERS` DOUBLE,
  `REGION_RATING_CLIENT` BIGINT,
  `REGION_RATING_CLIENT_W_CITY` BIGINT,
  `WEEKDAY_APPR_PROCESS_START` VARCHAR(30),
  `HOUR_APPR_PROCESS_START` BIGINT,
  `REG_REGION_NOT_LIVE_REGION` BIGINT,
  `REG_REGION_NOT_WORK_REGION` BIGINT,
  `LIVE_REGION_NOT_WORK_REGION` BIGINT,
  `REG_CITY_NOT_LIVE_CITY` BIGINT,
  `REG_CITY_NOT_WORK_CITY` BIGINT,
  `LIVE_CITY_NOT_WORK_CITY` BIGINT,
  `ORGANIZATION_TYPE` VARCHAR(32),
  `EXT_SOURCE_1` DOUBLE,
  `EXT_SOURCE_2` DOUBLE,
  `EXT_SOURCE_3` DOUBLE,
  `APARTMENTS_AVG` DOUBLE,
  `BASEMENTAREA_AVG` DOUBLE,
  `YEARS_BEGINEXPLUATATION_AVG` DOUBLE,
  `YEARS_BUILD_AVG` DOUBLE,
  `COMMONAREA_AVG` DOUBLE,
  `ELEVATORS_AVG` DOUBLE,
  `ENTRANCES_AVG` DOUBLE,
  `FLOORSMAX_AVG` DOUBLE,
  `FLOORSMIN_AVG` DOUBLE,
  `LANDAREA_AVG` DOUBLE,
  `LIVINGAPARTMENTS_AVG` DOUBLE,
  `LIVINGAREA_AVG` DOUBLE,
  `NONLIVINGAPARTMENTS_AVG` DOUBLE,
  `NONLIVINGAREA_AVG` DOUBLE,
  `APARTMENTS_MODE` DOUBLE,
  `BASEMENTAREA_MODE` DOUBLE,
  `YEARS_BEGINEXPLUATATION_MODE` DOUBLE,
  `YEARS_BUILD_MODE` DOUBLE,
  `COMMONAREA_MODE` DOUBLE,
  `ELEVATORS_MODE` DOUBLE,
  `ENTRANCES_MODE` DOUBLE,
  `FLOORSMAX_MODE` DOUBLE,
  `FLOORSMIN_MODE` DOUBLE,
  `LANDAREA_MODE` DOUBLE,
  `LIVINGAPARTMENTS_MODE` DOUBLE,
  `LIVINGAREA_MODE` DOUBLE,
  `NONLIVINGAPARTMENTS_MODE` DOUBLE,
  `NONLIVINGAREA_MODE` DOUBLE,
  `APARTMENTS_MEDI` DOUBLE,
  `BASEMENTAREA_MEDI` DOUBLE,
  `YEARS_BEGINEXPLUATATION_MEDI` DOUBLE,
  `YEARS_BUILD_MEDI` DOUBLE,
  `COMMONAREA_MEDI` DOUBLE,
  `ELEVATORS_MEDI` DOUBLE,
  `ENTRANCES_MEDI` DOUBLE,
  `FLOORSMAX_MEDI` DOUBLE,
  `FLOORSMIN_MEDI` DOUBLE,
  `LANDAREA_MEDI` DOUBLE,
  `LIVINGAPARTMENTS_MEDI` DOUBLE,
  `LIVINGAREA_MEDI` DOUBLE,
  `NONLIVINGAPARTMENTS_MEDI` DOUBLE,
  `NONLIVINGAREA_MEDI` DOUBLE,
  `FONDKAPREMONT_MODE` VARCHAR(31),
  `HOUSETYPE_MODE` VARCHAR(30),
  `TOTALAREA_MODE` DOUBLE,
  `WALLSMATERIAL_MODE` VARCHAR(30),
  `EMERGENCYSTATE_MODE` VARCHAR(30),
  `OBS_30_CNT_SOCIAL_CIRCLE` DOUBLE,
  `DEF_30_CNT_SOCIAL_CIRCLE` DOUBLE,
  `OBS_60_CNT_SOCIAL_CIRCLE` DOUBLE,
  `DEF_60_CNT_SOCIAL_CIRCLE` DOUBLE,
  `DAYS_LAST_PHONE_CHANGE` DOUBLE,
  `FLAG_DOCUMENT_2` BIGINT,
  `FLAG_DOCUMENT_3` BIGINT,
  `FLAG_DOCUMENT_4` BIGINT,
  `FLAG_DOCUMENT_5` BIGINT,
  `FLAG_DOCUMENT_6` BIGINT,
  `FLAG_DOCUMENT_7` BIGINT,
  `FLAG_DOCUMENT_8` BIGINT,
  `FLAG_DOCUMENT_9` BIGINT,
  `FLAG_DOCUMENT_10` BIGINT,
  `FLAG_DOCUMENT_11` BIGINT,
  `FLAG_DOCUMENT_12` BIGINT,
  `FLAG_DOCUMENT_13` BIGINT,
  `FLAG_DOCUMENT_14` BIGINT,
  `FLAG_DOCUMENT_15` BIGINT,
  `FLAG_DOCUMENT_16` BIGINT,
  `FLAG_DOCUMENT_17` BIGINT,
  `FLAG_DOCUMENT_18` BIGINT,
  `FLAG_DOCUMENT_19` BIGINT,
  `FLAG_DOCUMENT_20` BIGINT,
  `FLAG_DOCUMENT_21` BIGINT,
  `AMT_REQ_CREDIT_BUREAU_HOUR` DOUBLE,
  `AMT_REQ_CREDIT_BUREAU_DAY` DOUBLE,
  `AMT_REQ_CREDIT_BUREAU_WEEK` DOUBLE,
  `AMT_REQ_CREDIT_BUREAU_MON` DOUBLE,
  `AMT_REQ_CREDIT_BUREAU_QRT` DOUBLE,
  `AMT_REQ_CREDIT_BUREAU_YEAR` DOUBLE
);

-- 아래 경로를 실제 파일 위치로 맞춰주세요 (역슬래시 대신 슬래시 사용)
LOAD DATA LOCAL INFILE 'C:/Users/user/test_2026/credit_scoring/application_train.csv'
INTO TABLE application_train
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- 검증
SELECT COUNT(*) FROM application_train;

SET SQL_SAFE_UPDATES = 0;
UPDATE application_train SET AMT_GOODS_PRICE = NULL WHERE AMT_GOODS_PRICE = 0;
UPDATE application_train SET AMT_ANNUITY = NULL WHERE AMT_ANNUITY = 0;




-- 2.load_bureau

DROP TABLE IF EXISTS bureau;

CREATE TABLE bureau (
  `SK_ID_CURR` BIGINT,
  `SK_ID_BUREAU` BIGINT,
  `CREDIT_ACTIVE` VARCHAR(30),
  `CREDIT_CURRENCY` VARCHAR(30),
  `DAYS_CREDIT` BIGINT,
  `CREDIT_DAY_OVERDUE` BIGINT,
  `DAYS_CREDIT_ENDDATE` DOUBLE,
  `DAYS_ENDDATE_FACT` DOUBLE,
  `AMT_CREDIT_MAX_OVERDUE` DOUBLE,
  `CNT_CREDIT_PROLONG` BIGINT,
  `AMT_CREDIT_SUM` DOUBLE,
  `AMT_CREDIT_SUM_DEBT` DOUBLE,
  `AMT_CREDIT_SUM_LIMIT` DOUBLE,
  `AMT_CREDIT_SUM_OVERDUE` DOUBLE,
  `CREDIT_TYPE` VARCHAR(60),
  `DAYS_CREDIT_UPDATE` BIGINT,
  `AMT_ANNUITY` DOUBLE
);

-- 아래 경로를 실제 bureau.csv 위치로 맞춰주세요 (역슬래시 대신 슬래시 사용)
LOAD DATA LOCAL INFILE 'C:/Users/user/test_2026/credit_scoring/bureau.csv'
INTO TABLE bureau
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- 검증 (Kaggle 원본 기준 1,716,428행이 정상)
SELECT COUNT(*) FROM bureau;




-- 3.preprocessing
-- =========================================================
-- A_금융 최종 확정본 SQL
-- 팀 공통 구조: 1.결측 → 2.이상치(그대로) → 3.파생변수(NULLIF) → 4.로그변환(원본유지) → 5.원핫인코딩 → 6.LEFT JOIN(Bureau 포함)
-- 전제: application_train.csv → application_train 테이블, bureau.csv → bureau 테이블로 적재되어 있음
--
-- [최종 A_금융 18개]
--   원본 유지 4개: AMT_CREDIT, AMT_ANNUITY, AMT_GOODS_PRICE, AMT_INCOME_TOTAL
--   로그변환 4개: AMT_CREDIT_LOG, AMT_ANNUITY_LOG, AMT_GOODS_PRICE_LOG, AMT_INCOME_TOTAL_LOG
--   이진인코딩 1개: NAME_CONTRACT_TYPE_BIN
--   파생비율 3개 : LTV_GOODS, CREDIT_TO_INCOME, ANNUITY_TO_CREDIT
--   Bureau 6개  : BUREAU_LOAN_COUNT, BUREAU_ACTIVE_LOAN_COUNT, BUREAU_DAYS_OVERDUE_MAX,
--                 BUREAU_DAYS_OVERDUE_MEAN, BUREAU_DEBT_RATIO, BUREAU_NO_HISTORY_FLAG
--   합계 4+4+1+3+6 = 18개 ✓
-- =========================================================


-- ---------------------------------------------------------
-- [1단계] 결측 채우기 (Missing)
-- ---------------------------------------------------------

SET @median_annuity := (
  SELECT AVG(val) FROM (
    SELECT AMT_ANNUITY AS val, ROW_NUMBER() OVER (ORDER BY AMT_ANNUITY) AS rn, COUNT(*) OVER () AS cnt
    FROM application_train WHERE AMT_ANNUITY IS NOT NULL
  ) t WHERE rn IN (FLOOR((cnt + 1) / 2), CEIL((cnt + 1) / 2))
);

SET @median_goods := (
  SELECT AVG(val) FROM (
    SELECT AMT_GOODS_PRICE AS val, ROW_NUMBER() OVER (ORDER BY AMT_GOODS_PRICE) AS rn, COUNT(*) OVER () AS cnt
    FROM application_train WHERE AMT_GOODS_PRICE IS NOT NULL
  ) t WHERE rn IN (FLOOR((cnt + 1) / 2), CEIL((cnt + 1) / 2))
);

SELECT @median_annuity AS median_annuity, @median_goods AS median_goods;

DROP TABLE IF EXISTS step1_missing;

CREATE TABLE step1_missing AS
SELECT
    SK_ID_CURR,
    TARGET,
    NAME_CONTRACT_TYPE,
    AMT_CREDIT,
    AMT_INCOME_TOTAL,
    COALESCE(AMT_ANNUITY, @median_annuity)   AS AMT_ANNUITY,
    COALESCE(AMT_GOODS_PRICE, @median_goods) AS AMT_GOODS_PRICE
FROM application_train;


-- ---------------------------------------------------------
-- [2단계] 이상치는 그대로 두기 (Outliers)
-- ---------------------------------------------------------


-- ---------------------------------------------------------
-- [3단계] 파생변수 만들기 (분모 NULLIF 필수)
-- LTV_GOODS, CREDIT_TO_INCOME, ANNUITY_TO_CREDIT
-- ---------------------------------------------------------

DROP TABLE IF EXISTS step3_derived;

CREATE TABLE step3_derived AS
SELECT
    SK_ID_CURR,
    AMT_CREDIT  / NULLIF(AMT_GOODS_PRICE, 0)   AS LTV_GOODS,
    AMT_CREDIT  / NULLIF(AMT_INCOME_TOTAL, 0)  AS CREDIT_TO_INCOME,
    AMT_ANNUITY / NULLIF(AMT_CREDIT, 0)        AS ANNUITY_TO_CREDIT
FROM step1_missing;


-- ---------------------------------------------------------
-- [4단계] 로그 변환 (원본은 남기기)
-- ---------------------------------------------------------

DROP TABLE IF EXISTS step4_log;

CREATE TABLE step4_log AS
SELECT
    SK_ID_CURR,
    LN(AMT_CREDIT + 1)       AS AMT_CREDIT_LOG,
    LN(AMT_ANNUITY + 1)      AS AMT_ANNUITY_LOG,
    LN(AMT_GOODS_PRICE + 1)  AS AMT_GOODS_PRICE_LOG,
    LN(AMT_INCOME_TOTAL + 1) AS AMT_INCOME_TOTAL_LOG
FROM step1_missing;


-- ---------------------------------------------------------
-- [5단계] 원핫 인코딩
-- NAME_CONTRACT_TYPE은 범주 2개뿐이라 이진 인코딩(원핫과 동치) — Cash: 0, Revolving: 1
-- ---------------------------------------------------------

DROP TABLE IF EXISTS step5_encoded;

CREATE TABLE step5_encoded AS
SELECT
    SK_ID_CURR,
    CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' THEN 0
         WHEN NAME_CONTRACT_TYPE = 'Revolving loans' THEN 1
         ELSE NULL END AS NAME_CONTRACT_TYPE_BIN
FROM step1_missing;


-- ---------------------------------------------------------
-- [Bureau] bureau.csv 집계변수 6개 (SK_ID_CURR 단위)
-- ---------------------------------------------------------

DROP TABLE IF EXISTS bureau_features;

CREATE TABLE bureau_features AS
SELECT
    ids.SK_ID_CURR,
    COALESCE(agg.BUREAU_LOAN_COUNT, 0)        AS BUREAU_LOAN_COUNT,
    COALESCE(agg.BUREAU_ACTIVE_LOAN_COUNT, 0) AS BUREAU_ACTIVE_LOAN_COUNT,
    COALESCE(agg.BUREAU_DAYS_OVERDUE_MAX, 0)  AS BUREAU_DAYS_OVERDUE_MAX,
    COALESCE(agg.BUREAU_DAYS_OVERDUE_MEAN, 0) AS BUREAU_DAYS_OVERDUE_MEAN,
    COALESCE(agg.BUREAU_DEBT_RATIO, 0)        AS BUREAU_DEBT_RATIO,
    CASE WHEN agg.SK_ID_CURR IS NULL THEN 1 ELSE 0 END AS BUREAU_NO_HISTORY_FLAG
FROM (SELECT DISTINCT SK_ID_CURR FROM application_train) ids
LEFT JOIN (
    SELECT
        b.SK_ID_CURR,
        COUNT(*) AS BUREAU_LOAN_COUNT,
        SUM(CASE WHEN b.CREDIT_ACTIVE = 'Active' THEN 1 ELSE 0 END) AS BUREAU_ACTIVE_LOAN_COUNT,
        MAX(b.CREDIT_DAY_OVERDUE) AS BUREAU_DAYS_OVERDUE_MAX,
        AVG(b.CREDIT_DAY_OVERDUE) AS BUREAU_DAYS_OVERDUE_MEAN,
        -- pandas groupby().sum()은 전부 NULL이어도 0을 반환 → MySQL SUM과 다르므로 COALESCE로 맞춤
        CASE WHEN SUM(COALESCE(b.AMT_CREDIT_SUM, 0)) > 0
             THEN SUM(COALESCE(b.AMT_CREDIT_SUM_DEBT, 0)) / SUM(COALESCE(b.AMT_CREDIT_SUM, 0))
             ELSE 0 END AS BUREAU_DEBT_RATIO
    FROM bureau b
    GROUP BY b.SK_ID_CURR
) agg ON ids.SK_ID_CURR = agg.SK_ID_CURR;


-- ---------------------------------------------------------
-- [6단계] LEFT JOIN으로 합치기 → 최종 A_금융 18개 + ID/TARGET
-- ---------------------------------------------------------

DROP TABLE IF EXISTS model_A_final;

CREATE TABLE model_A_final AS
SELECT
    m.SK_ID_CURR,
    m.TARGET,
    e.NAME_CONTRACT_TYPE_BIN,
    m.AMT_CREDIT,
    l.AMT_CREDIT_LOG,
    m.AMT_ANNUITY,
    l.AMT_ANNUITY_LOG,
    m.AMT_GOODS_PRICE,
    l.AMT_GOODS_PRICE_LOG,
    m.AMT_INCOME_TOTAL,
    l.AMT_INCOME_TOTAL_LOG,
    d.LTV_GOODS,
    d.CREDIT_TO_INCOME,
    d.ANNUITY_TO_CREDIT,
    bu.BUREAU_LOAN_COUNT,
    bu.BUREAU_ACTIVE_LOAN_COUNT,
    bu.BUREAU_DAYS_OVERDUE_MAX,
    bu.BUREAU_DAYS_OVERDUE_MEAN,
    bu.BUREAU_DEBT_RATIO,
    bu.BUREAU_NO_HISTORY_FLAG
FROM step1_missing m
LEFT JOIN step3_derived   d  ON m.SK_ID_CURR = d.SK_ID_CURR
LEFT JOIN step4_log       l  ON m.SK_ID_CURR = l.SK_ID_CURR
LEFT JOIN step5_encoded   e  ON m.SK_ID_CURR = e.SK_ID_CURR
LEFT JOIN bureau_features bu ON m.SK_ID_CURR = bu.SK_ID_CURR;


-- ---------------------------------------------------------
-- 최종 검증
-- ---------------------------------------------------------

SELECT COUNT(*), COUNT(DISTINCT SK_ID_CURR), SUM(TARGET)
FROM model_A_final;
